variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  firex_base_logging_dir: "$CI_PROJECT_DIR/flow_test_results"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test
  - upload
  - update-docs

default:
  image: firexstuff/firex-alpine-build:3.10.9
  before_script:
    - source venv/bin/activate
    - git config --global --add safe.directory /builds/FireXStuff/firex-flame

build:
  stage: build
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade firexbuilder
    - git config --global --add safe.directory /builds/FireXStuff/firex-flame
  script:
    - firex-build build --install_test_reqs
  after_script:
    - source venv/bin/activate
    - pip freeze
  artifacts:
    paths:
      - dist/

build-docs:
  stage:  test
  script:
    - firex-build docs
  artifacts:
    paths:
      - html/

test-unit:
  stage: test
  script:
    - firex-build unit_tests
  artifacts:
    paths:
      - .coverage

test-integration:
  stage: test
  script:
    - pip install --upgrade firex-bundle-ci
    - pip install firex-keeper
    - sudo /usr/sbin/sshd
    - firexapp submit --chain RunAllIntegrationTests --public_runs True --install_configs cloud-ci-install-configs.json --sync --coverage False --max_parallel_tests 5
  artifacts:
    paths:
      - flow_test_results/
    when: always

upload-codecov:
  stage: upload
  script:
    - firex-build upload_codecov
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

upload-results:
  inherit:
    default: false
  stage: upload
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
    - gsutil -m rsync -e -r $firex_base_logging_dir  gs://runs.firexflame.com
  when: always

upload-pkg:
  stage: upload
  script:
    - pip install keyrings.alt
    - firex-build upload_pip
  only:
    - tags

update-docs:
  inherit:
    default: false
  stage: update-docs
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
    - gsutil -m rsync -r html gs://www.firexstuff.com/firex-flame
  needs:
    - upload-pkg
    - build-docs
  only:
    - tags
