variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  firex_base_logging_dir: "$CI_PROJECT_DIR/flow_test_results"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - upload

   
build:
  stage: build
  image: firexstuff/firex-alpine-build
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade firexbuilder
  script:
    - pip install keyrings.alt
    - firex-build all --skip_htmlcov --upload_codecov --upload_pip_if_tag --install_test_reqs --install_flame
  artifacts:
    paths:
      - html/
      - flow_test_results/
    when: always
   
upload-results:
  stage: upload
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS 
    - gsutil -m rsync -e -r flow_test_results/FireX-*  gs://runs.firexflame.com

upload-docs:
  stage: upload
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS 
    - gsutil -m rsync -r html gs://www.firexapp.com
  only:
    - tags